# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          DOCKER_USERNAME: secrethub://stavalfi/dockerhub/username
          DOCKER_PASSWORD: secrethub://stavalfi/dockerhub/access-token
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
      - name: install k8s
        uses: engineerd/setup-kind@v0.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: eval $(minikube docker-env)
      - run: yarn workspace simple-service build:docker
      - run: yarn workspace k8test-monitoring build:docker
      - run: yarn test
